#!/usr/bin/env php
<?php

use Jfortunato\ImageOptimizer\OptimizeImages;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputArgument;

// set to run indefinitely if needed
set_time_limit(0);

require_once __DIR__ . '/vendor/autoload.php';

(new Application('optimize-images', '0.1.0'))
    ->register('optimize-images')
    ->addArgument('input-directory', InputArgument::REQUIRED, "The input directory with unoptimized images.")
    ->addArgument('output-directory', InputArgument::REQUIRED, "The output directory where the optimized images will go.")
    ->setCode(new OptimizeImages)
    ->getApplication()
    ->setDefaultCommand('optimize-images', true) // Single command application
    ->run();
